.TH chocolate\-server 6
.SH NAME
chocolate\-server \- dedicated server for chocolate\-doom
.SH SYNOPSIS
.B chocolate\-server
.SH DESCRIPTION
.PP
Chocolate Doom is a modern server engine designed to behave
as similar to the original server game as is possible.
.PP
.B chocolate\-server
is a dedicated server for Chocolate Doom. It takes no arguments;
game options are specified by the first player to join the game,
who is designated the controlling player.
.br
.SH AUTHOR
Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-7 Simon Howard.
