.TH chocolate\-setup 6
.SH NAME
chocolate\-setup \- settings tool for chocolate\-doom
.SH SYNOPSIS
.B chocolate\-server
.SH DESCRIPTION
.PP
Chocolate Doom is a modern server engine designed to behave
as similar to the original server game as is possible.
.PP
.B chocolate\-server
is a tool for configuring Chocolate Doom. It provides a menu\-based
interface for setting your Display, Joystick, Keyboard, Mouse, Sound and
compatibility settings.
.PP
.B chocolate\-server
also allows you to start and join network games.
.PP
.B chocolate\-server
accepts no command\-line options.
.br
.SH AUTHOR
Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-7 Simon Howard.
