.TH cnsetup 6
.SH NAME
cnsetup \- configuration tool for cndoom
.SH SYNOPSIS
.B cnsetup
[OPTIONS]
.SH DESCRIPTION
.PP
Competition Doom is a modern Doom engine designed to behave
as similar to the original Doom game as is possible.
.PP
.B cnsetup
is a tool for configuring Competition Doom. It provides a menu\-based
interface for the display, joystick, keyboard, mouse, sound and
compatibility settings.
.PP
.B cnsetup
can also be used to start and join network games.
.PP
.SH OPTIONS
.TP
\fB-config <file>\fR
Load configuration from the specified file, instead of default.cfg. 
.TP
\fB-extraconfig <file>\fR
Load extra configuration from the specified file, instead of cndoom.cfg. 
.SH SEE ALSO
\fBcndoom\fR(6),
\fBdefault.cfg\fR(5),
\fBcndoom.cfg\fR(5)
.SH AUTHOR
Competition Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-8 Simon Howard.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

