.TH lemon\-setup 6
.SH NAME
lemon\-setup \- configuration tool for lemon\-doom
.SH SYNOPSIS
.B lemon\-setup
[OPTIONS]
.SH DESCRIPTION
.PP
Lemon Doom is a simple hack of Chocolate Doom that raises the limits
to those of Doom-Plus, without doing anything else. Refer to the Chocolate 
Doom documentation for a description of Chocolate Doom. 
.PP
.B lemon\-setup
is a tool for configuring Lemon Doom. It provides a menu\-based
interface for the display, joystick, keyboard, mouse, sound and
compatibility settings.
.PP
.B lemon\-setup
could theoretically also be used to start and join network games, but
the author is a dummy & doesn't know how this would work.
.PP
.SH OPTIONS
.TP
\fB-config <file>\fR
Load configuration from the specified file, instead of default.cfg. 
.TP
\fB-extraconfig <file>\fR
Load extra configuration from the specified file, instead of chocolate-doom.cfg. 
.SH SEE ALSO
\fBlemon-doom\fR(6),
\fBdefault.cfg\fR(5),
\fBlemon-doom.cfg\fR(5)
.SH AUTHOR
Lemon Doom is maintained by Mike DeRoitr.
The original Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland & Mike DeRoitr.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-8 Simon Howard.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

