#!/bin/sh

if [ -e INSTALL ]; then
    have_INSTALL=true
else
    have_INSTALL=false
fi

mkdir -p autotools

aclocal
autoheader
automake -ac
autoconf
automake

# The INSTALL file is autogenerated, so it isn't stored in version control.
# As the file isn't present, automake's -a option will install generic
# install instructions.  So remove INSTALL if automake installed one.

if ! $have_INSTALL; then
    rm -f INSTALL
fi

./configure "$@"

