ifeq ($(V),1)
	VB=
else
	VB=@
endif

CC=clang
CXX=clang++
SYSOP_ROOT=/root/Sysop-64/linux-code
SYSOP_INCLUDE=$(SYSOP_ROOT)/libsysop64/include
SYSOP_LIB=$(SYSOP_ROOT)/build/lib/libsysop64.a
THREAD_FLAGS=-pthread
OBJDIR=build-sysop64
OUTPUT=chocolate-doom-sysop64

SRC_DIR=src
DOOM_DIR=src/doom
SYSOP64_DIR=src/sysop64
VPATH=$(SRC_DIR):$(DOOM_DIR):$(SYSOP64_DIR)

COMMON_CFLAGS=-ggdb3 -Os -Wall -DNORMALUNIX -DLINUX -D_DEFAULT_SOURCE -I$(SRC_DIR) -I$(DOOM_DIR) -I$(SYSOP64_DIR) -I$(SYSOP_INCLUDE) -mfpu=neon -mfloat-abi=hard $(THREAD_FLAGS)
CFLAGS+=$(COMMON_CFLAGS)
CXXFLAGS+=$(COMMON_CFLAGS) -std=c++17
LDFLAGS+=-Wl,--gc-sections
LIBS+=$(SYSOP_LIB) -lm -lc $(THREAD_FLAGS)

SYSOP64_C_OBJS = \
	i_sysop64_main.o i_sysop64.o net_sysop64.o net_sysop64_gui.o \
	sysop64_keyboard.o sysop64_mouse.o sysop64_joystick.o sysop64_sound.o \
	sysop64_image.o sysop64_image_mega.o sysop64_tune_http.o

SYSOP64_CPP_OBJS = \
	sid_player_bridge.o

COMMON_OBJS = \
	$(SYSOP64_C_OBJS) \
	aes_prng.o d_event.o d_iwad.o d_loop.o d_mode.o \
	deh_str.o gusconf.o i_glob.o m_argv.o m_bbox.o m_cheat.o \
	m_config.o m_controls.o m_fixed.o m_misc.o net_client.o net_common.o \
	net_dedicated.o net_io.o net_loop.o net_packet.o net_petname.o net_query.o \
	net_server.o net_structrw.o p_rejectpad.o \
	sha1.o memio.o tables.o v_diskicon.o v_video.o w_checksum.o w_file.o \
	w_file_stdc.o w_main.o w_merge.o w_wad.o z_zone.o deh_io.o deh_main.o \
	deh_mapping.o deh_text.o

DOOM_OBJS = \
	am_map.o deh_ammo.o deh_bexstr.o deh_cheat.o deh_doom.o deh_frame.o \
	deh_misc.o deh_ptr.o deh_sound.o deh_thing.o deh_weapon.o d_items.o \
	d_main.o d_net.o doomdef.o doomstat.o dstrings.o f_finale.o f_wipe.o \
	g_game.o hu_lib.o hu_stuff.o info.o m_menu.o m_random.o p_ceilng.o \
	p_doors.o p_enemy.o p_floor.o p_inter.o p_lights.o p_map.o p_maputl.o \
	p_mobj.o p_plats.o p_pspr.o p_saveg.o p_setup.o p_sight.o p_spec.o \
	p_switch.o p_telept.o p_tick.o p_user.o r_bsp.o r_data.o r_draw.o \
	r_main.o r_plane.o r_segs.o r_sky.o r_things.o s_sound.o sounds.o \
	statdump.o st_lib.o st_stuff.o wi_stuff.o

CPP_OBJS = $(SYSOP64_CPP_OBJS)
OBJS = $(addprefix $(OBJDIR)/,$(COMMON_OBJS) $(DOOM_OBJS) $(CPP_OBJS))

all: $(OUTPUT)

clean:
	rm -rf $(OBJDIR)
	rm -f $(OUTPUT) $(OUTPUT).map

$(OUTPUT): $(OBJS)
	@echo [Linking $@]
	$(VB)$(CXX) $(CXXFLAGS) $(LDFLAGS) $(OBJS) -o $(OUTPUT) $(LIBS) -Wl,-Map,$(OUTPUT).map
	@echo [Size]
	-$(CROSS_COMPILE)size $(OUTPUT)

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: %.c
	@echo [Compiling $<]
	$(VB)$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o: %.cpp
	@echo [Compiling C++ $<]
	$(VB)$(CXX) $(CXXFLAGS) -c $< -o $@

print:
	@echo OBJS: $(OBJS)
