# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
STRIP = strip

# Package name and version number:

PROGRAM_PREFIX = cn
PACKAGE = cndoom
PACKAGE_NAME = Competition Doom
PACKAGE_STRING = Competition Doom 2.0.3.1
PACKAGE_TARNAME = cndoom
PACKAGE_VERSION = 2.0.3.1

# Documentation files to distribute with packages.

DOC_FILES = README        \
            ChangeLog


