name: cppcheck

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  cppcheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cppcheck

      - uses: actions/checkout@v6

      - name: Run cppcheck
        run: |
          cppcheck --error-exitcode=1 -j2 -UTESTING -D__GNUC__ -Iopl -Isrc -Isrc/setup opl pcsound src textscreen 2> stderr.txt
          RET=$?
          if [ -s stderr.txt ]; then
            cat stderr.txt
          fi
          exit $RET
