name: GCC static analyzer

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  analyzer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libfluidsynth-dev libpng-dev libsamplerate0-dev libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev

      - name: Configure
        env:
          CFLAGS: -O2 -fanalyzer
        run: |
          ./autogen.sh --enable-werror

      - name: Build
        run: make -j4 -k

