name: macos

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: brew install ninja sdl2 sdl2_image sdl2_mixer sdl2_net

      - uses: actions/checkout@v2

      - name: CMake
        run: cmake -S . -B build -G Ninja && ninja -C build

      - name: Make
        run: $GITHUB_WORKSPACE/.travis.sh
